kind: Service
apiVersion: v1
metadata:
  name: connectionsposts-svc
spec:
  selector:
    app: connectionsposts
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectionsposts
  labels:
    app: connectionsposts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: connectionsposts
  template:
    metadata:
      labels:
        app: connectionsposts
    spec:
      containers:
        - name: connectionsposts
          image: cdavisafc/cloudnative-appconfig-connectionposts:0.0.1
          env:
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CONNECTIONPOSTSCONTROLLER_POSTSURL
              value: 'http://192.168.64.3:31951/posts?userIds='
            - name: CONNECTIONPOSTSCONTROLLER_CONNECTIONSURL
              value: 'http://192.168.64.3:30235/connections/'
            - name: CONNECTIONPOSTSCONTROLLER_USERSURL
              value: 'http://192.168.64.3:30235/users/'
            - name: REDIS_HOSTNAME
              value: '192.168.64.3'
            - name: REDIS_PORT
              value: '32092'
